sudo: required
dist: trusty

language: java

services:
  - docker

jdk: oraclejdk8

addons:
  sonarqube:
    organization: "vorto"
    token:
      secure: $SONAR_TOKEN

before_install: echo "MAVEN_OPTS='-Xms1g -Xmx2g -XX:PermSize=512m -XX:MaxPermSize=1g'" > ~/.mavenrc

install: true
script:
  - sonar-scanner
  - mvn clean install -f pom.xml
  - bash <(curl -s https://codecov.io/bash)
  

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

